//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UIDesign
{
    using System;
    using System.Collections.Generic;
    
    public partial class competitior_price
    {
        public int CompetitiorID { get; set; }
        public string ItemID { get; set; }
        public string MemberID { get; set; }
        public string DCID { get; set; }
        public double CompetitiorPrice { get; set; }
        public string Approval { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public System.DateTime ApprovalDate { get; set; }
    
        public virtual competitor competitor { get; set; }
        public virtual dealer_customer dealer_customer { get; set; }
        public virtual item item { get; set; }
        public virtual member member { get; set; }
    }
}
