//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UIDesign
{
    using System;
    using System.Collections.Generic;
    
    public partial class competitor
    {
        public competitor()
        {
            this.competitior_price = new HashSet<competitior_price>();
        }
    
        public int CompetitorID { get; set; }
        public string CompetitorName { get; set; }
        public string CompetitorDescription { get; set; }
    
        public virtual ICollection<competitior_price> competitior_price { get; set; }
    }
}
