//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UIDesign
{
    using System;
    using System.Collections.Generic;
    
    public partial class item
    {
        public item()
        {
            this.competitior_price = new HashSet<competitior_price>();
            this.store_item = new HashSet<store_item>();
            this.purchase_orderline = new HashSet<purchase_orderline>();
            this.quotation_item = new HashSet<quotation_item>();
            this.reserve_request = new HashSet<reserve_request>();
            this.sales_orderline = new HashSet<sales_orderline>();
        }
    
        public string ItemID { get; set; }
        public string ItemName { get; set; }
        public string ItemType { get; set; }
        public string ItemDescription { get; set; }
        public double ItemPrice { get; set; }
        public Nullable<double> StreetSellingPriceMax { get; set; }
        public Nullable<double> StreetSellingPriceMin { get; set; }
    
        public virtual ICollection<competitior_price> competitior_price { get; set; }
        public virtual ICollection<store_item> store_item { get; set; }
        public virtual ICollection<purchase_orderline> purchase_orderline { get; set; }
        public virtual ICollection<quotation_item> quotation_item { get; set; }
        public virtual ICollection<reserve_request> reserve_request { get; set; }
        public virtual ICollection<sales_orderline> sales_orderline { get; set; }
    }
}
