//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UIDesign
{
    using System;
    using System.Collections.Generic;
    
    public partial class member_type
    {
        public member_type()
        {
            this.member = new HashSet<member>();
            this.member_discount = new HashSet<member_discount>();
        }
    
        public int TypeID { get; set; }
        public string TypeName { get; set; }
    
        public virtual ICollection<member> member { get; set; }
        public virtual ICollection<member_discount> member_discount { get; set; }
    }
}
