//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UIDesign
{
    using System;
    using System.Collections.Generic;
    
    public partial class member
    {
        public member()
        {
            this.competitior_price = new HashSet<competitior_price>();
            this.quotation = new HashSet<quotation>();
            this.reserve_request = new HashSet<reserve_request>();
            this.sales_order = new HashSet<sales_order>();
        }
    
        public string MemberID { get; set; }
        public int TypeID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string HKID { get; set; }
        public string Phone { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<competitior_price> competitior_price { get; set; }
        public virtual member_type member_type { get; set; }
        public virtual ICollection<quotation> quotation { get; set; }
        public virtual ICollection<reserve_request> reserve_request { get; set; }
        public virtual ICollection<sales_order> sales_order { get; set; }
    }
}
