//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UIDesign
{
    using System;
    using System.Collections.Generic;
    
    public partial class reserve_request
    {
        public int RequestID { get; set; }
        public string ItemID { get; set; }
        public int StoreID { get; set; }
        public string MemberID { get; set; }
        public string DCID { get; set; }
        public System.DateTime SendRequestDate { get; set; }
        public System.DateTime ReserveDate { get; set; }
    
        public virtual dealer_customer dealer_customer { get; set; }
        public virtual item item { get; set; }
        public virtual member member { get; set; }
        public virtual store store { get; set; }
    }
}
