//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UIDesign
{
    using System;
    using System.Collections.Generic;
    
    public partial class staff
    {
        public staff()
        {
            this.purchase_order = new HashSet<purchase_order>();
            this.quotation = new HashSet<quotation>();
            this.sales_order = new HashSet<sales_order>();
        }
    
        public string StaffID { get; set; }
        public int StoreID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public string HKID { get; set; }
        public string Password { get; set; }
        public string Phone { get; set; }
        public System.DateTime DOB { get; set; }
        public System.DateTime DOE { get; set; }
        public Nullable<System.DateTime> DOL { get; set; }
        public int SOR { get; set; }
        public int CRM { get; set; }
        public int INV { get; set; }
        public int ENQ { get; set; }
    
        public virtual ICollection<purchase_order> purchase_order { get; set; }
        public virtual ICollection<quotation> quotation { get; set; }
        public virtual ICollection<sales_order> sales_order { get; set; }
        public virtual store store { get; set; }
    }
}
