//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UIDesign
{
    using System;
    using System.Collections.Generic;
    
    public partial class store
    {
        public store()
        {
            this.purchase_order = new HashSet<purchase_order>();
            this.reserve_request = new HashSet<reserve_request>();
            this.sales_order = new HashSet<sales_order>();
            this.staff = new HashSet<staff>();
            this.store_item = new HashSet<store_item>();
        }
    
        public int StoreID { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Nickname { get; set; }
    
        public virtual ICollection<purchase_order> purchase_order { get; set; }
        public virtual ICollection<reserve_request> reserve_request { get; set; }
        public virtual ICollection<sales_order> sales_order { get; set; }
        public virtual ICollection<staff> staff { get; set; }
        public virtual ICollection<store_item> store_item { get; set; }
    }
}
